import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const GENERATED = '<!-- generated by scripts/sync_agents.mjs -->\n';

function parseAliases(line) {
  if (!line) return [];
  return line
    .split(',')
    .map((value) => value.trim())
    .filter(Boolean);
}

export function readSkillCatalog(root) {
  const skillsDir = join(root, 'skills');
  const entries = readdirSync(skillsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => existsSync(join(skillsDir, name, 'SKILL.md')));

  const catalog = entries.map((slug) => {
    const filePath = join(skillsDir, slug, 'SKILL.md');
    const text = readFileSync(filePath, 'utf8');
    const title = text.match(/^#\s+(.+)$/m)?.[1]?.trim();
    const useWhen = text.match(/^\*\*Use this when:\*\*\s+(.+)$/m)?.[1]?.trim();
    const aliasesLine = text.match(/^\*\*Aliases:\*\*\s+(.+)$/m)?.[1]?.trim();
    if (!title || !useWhen) {
      throw new Error(`Skill ${slug} is missing a title or a \"Use this when\" line.`);
    }
    return {
      slug,
      title,
      useWhen,
      aliases: parseAliases(aliasesLine)
    };
  });

  return catalog.sort((a, b) => {
    if (a.slug === 'office-hours') return -1;
    if (b.slug === 'office-hours') return 1;
    return a.slug.localeCompare(b.slug);
  });
}

function buildCommandWrapper(commandName, canonicalSlug) {
  return `${GENERATED}Use the \`jailbreak-university/${canonicalSlug}\` skill.\n\nUser input: $ARGUMENTS\n\nFollow the skill exactly.\nIf the user gave too little context, ask the minimum necessary questions and then move.\nKeep the answer in the repo's voice: direct, useful, concrete, slightly irreverent, and alive.\nObey \`docs/SAFETY.md\`.\n`;
}

function buildCommandIndex(catalog) {
  const lines = [
    GENERATED.trimEnd(),
    '# Command index',
    '',
    'This file is generated from `skills/*/SKILL.md`. Edit the skill, then run `npm run sync`.',
    ''
  ];

  for (const skill of catalog) {
    lines.push(`## \`/${skill.slug}\``);
    lines.push(skill.useWhen);
    if (skill.aliases.length > 0) {
      lines.push('');
      lines.push(`Aliases: ${skill.aliases.map((alias) => `\`/${alias}\``).join(', ')}`);
    }
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

export function buildArtifacts(root) {
  const catalog = readSkillCatalog(root);
  const commands = new Map();

  for (const skill of catalog) {
    commands.set(`${skill.slug}.md`, buildCommandWrapper(skill.slug, skill.slug));
    for (const alias of skill.aliases) {
      commands.set(`${alias}.md`, buildCommandWrapper(alias, skill.slug));
    }
  }

  return {
    catalog,
    commands,
    commandIndex: buildCommandIndex(catalog)
  };
}

function writeIfChanged(path, content) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current !== content) {
    writeFileSync(path, content);
  }
}

export function sync(root) {
  const { commands, commandIndex } = buildArtifacts(root);
  const commandsDir = join(root, 'commands');
  const docsDir = join(root, 'docs');

  mkdirSync(commandsDir, { recursive: true });
  mkdirSync(docsDir, { recursive: true });

  const existing = readdirSync(commandsDir).filter((name) => name.endsWith('.md'));
  for (const name of existing) {
    if (!commands.has(name)) {
      rmSync(join(commandsDir, name));
    }
  }

  for (const [name, content] of commands.entries()) {
    writeIfChanged(join(commandsDir, name), content);
  }

  writeIfChanged(join(docsDir, 'COMMAND_INDEX.md'), commandIndex);
}

const isDirectRun = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isDirectRun) {
  const root = join(__dirname, '..');
  sync(root);
}
